### ISSUE TITLE
Mean temperature for all years, grouped by month

### ISSUE THREAD

**Issue by enniomara** [AnttonLA/MNXB01-project#3]
For a city (not sure which at this point), calculate the monthly temperature average and compare it with the previous years. 

The resulting graph would have the years on the x-axis, temperature on the y axis, and 12 lines, one for each month of the year.

**Comment by enniomara** [comment]
@AnttonLA what do you think about having this as the idea that does not come from section 3?

**Comment by AnttonLA** [comment]
Hey @enniomara, I like the idea a lot!
If you make it a member function of tempTrender then it can be called for whatever city is given in the link when creating the object. See the code we've been using to parse the .csv files for reference.
Best of luck! Let us know if we can help you with anything!
